name: static-files-generation

on:
  schedule:
  - cron: '0 2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install APT Packages
        run: sudo apt install exuberant-ctags make
      
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.8
          cache: 'poetry'

      - name: Generate files from the latest kernel
        run: |
          poetry install
          poetry run python3 gen_syscalls.py FETCH
      
      - name: Deploy
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          bash deploy.sh
